Merge Feature Branch to Master
RamseyNjire/the-news-week-clone pull request #1
Opened 2020-05-13 21:31 UTC by RamseyNjire

This is an attempt to reproduce the Newsweek with Bootstrap 4. I reproduced the main parts of the website so not all the components on the original will appear in my clone. The main aim was to recreate a believable clone and use Bootstrap to handle most of the responsiveness. I only used media queries to handle the display of the header on screens of different sizes. I hope you like it!

2020-05-14 02:25 UTC, trekab requested changes
# Changes required!
Hi @RamseyNjire, well done with the project so far! :+1: However, there are some changes you need to make to complete this project. These include;
- [x] Your main navigation lacks the search input and icon and it has too much white space to the rightmost end.([Your clone](https://github.com/trekab/images/blob/master/ramsey/your_clone_main_nav.png?raw=true) Vs [Original](https://github.com/trekab/images/blob/master/ramsey/org_main_nv.png?raw=true))
- [x] Missing Humberger icon for navigation on medium and small screens. ([Your clone](https://github.com/trekab/images/blob/master/ramsey/top_story_clone.png?raw=true) Vs [Original](https://github.com/trekab/images/blob/master/ramsey/top_story_org.png?raw=true))
- [x] Featured slide show sections have too much space between images and text on the right. ([Your clone](https://github.com/trekab/images/blob/master/ramsey/slideshows_clone.png?raw=true) Vs [Original](https://github.com/trekab/images/blob/master/ramsey/slideshows_org.png?raw=true)).
- [x] `TOP STORY` should appear on top for small screens. ([Your clone](https://github.com/trekab/images/blob/master/ramsey/top_story_clone.png?raw=true) Vs [Original](https://github.com/trekab/images/blob/master/ramsey/top_story_org.png?raw=true))
- [x] `MORE STORIES` links aren't styled like the original's links.

__Kindly work on the above changes and submit another code review request.__
_Feel free to reach me on slack for inquiries about this review!_ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-05-15 21:42 UTC, RamseyNjire commented
Hey, Treasure! So I fixed all the errors you pointed out, including building the missing components (searchbar and hamburger icon). A note to be made is that some spacing issues may be due to you having a 15-inch or larger screen, as the layout seems okay otherwise. I hope you like the improvements! :)

2020-05-16 18:50 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved, kindly implement the changes listed below.

### Happy coding! :computer:

## Lucas Mazo

2020-05-16 18:50 UTC, lucasmazo32 commented on index.html
> +                </li>
- [ ] Kindly fix the W3C validator error.

> ![image](https://user-images.githubusercontent.com/57414789/82127669-07737480-977b-11ea-9126-5fc38a231781.png)

2020-05-16 18:50 UTC, lucasmazo32 commented on index.html
> +              </div>
- [ ] You can set the container fluid to have a max-width of 1310px as the original page. This wa you will not have an problems with large screens.

2020-05-17 10:50 UTC, RamseyNjire commented
Finished implementing the changes. Fixed the W3C validation errors as well as setting maximum width for .container-fluid to 1310 px

2020-05-18 18:29 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-18 18:32 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @RamseyNjire, congratulations on fixing all the changes recommended by the previous TSE's :+1: On this note, I hereby approve your project. You can go ahead and merge to master and do not forget to submit the project completion form :slightly_smiling_face: 

 Good luck with your next projects
_HAPPY CODING_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-05-18 18:34 UTC, merged